# server config
server:
  port: 8000
  error:
    include-stacktrace: always
  compression:
    enabled: true
  address: 0.0.0.0

# spring config
spring:
  jackson:
    # This is responsible for convert java data class to json & vice versa.
    #This is by default available of spring boot project.
    date-format: yyyy-MM-dd
  application:
    name: learning-spring-boot
  batch:
    job:
      enabled: true
    jdbc:
      initialize-schema: always
  main:
      allow-bean-definition-overriding: true