# For developments environments

# server config
server:
  port: 8001
  error:
    include-stacktrace: always
  compression:
    enabled: true
  address: 0.0.0.0

spring:
  # Database Configuration
  datasource:
#    url: jdbc:mysql://localhost:3306/LEARNING_SPRING_BOOT
#    url: jdbc:mysql://${DB_SERVER:localhost}:${DB_PORT:3306}/${DB_NAME}
    url: ${MYSQL_SERVER}
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:Root12!@}
    driver-class-name: ${DB_DRIVER_CLASS_NAME:com.mysql.jdbc.Driver}

  # JPA Configuration
  jpa:
    # Properties
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        naming:
          implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        show_sql: true
        format_sql: true
        use_sql: true
        shutdown_on_session_factory_close: false
        connection:
          characterEncoding: utf-8
          CharSet: utf-8
          useUnicode: true
          legacy_limit_handler: true

    # Hibernate
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
